version: "3"

services:
  db:
    image: postgres
    container_name: bus_routes_postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bus_routes_app
    environment:
      SECRET_KEY: clave_secreta_para_generar_tokens_jwt
      DATABASE_URL: postgresql://username:password@db:5432/busroutes
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data: